<?xml version="1.0" encoding="utf-8"?><Database Name="narfdaddy2" Class="narfdaddy2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=184.168.194.77;Initial Catalog=narfdaddy2;User ID=narfdaddy2;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="narfdaddy2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="narfdaddy2.ListBuilder1" Member="ListBuilder1s">
    <Type Name="ListBuilder1">
      <Column Name="numRow" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sCat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sSubcat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sItem" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sDialog" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>