#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="narfdaddy2")]
	public partial class narfdaddy2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public narfdaddy2DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["narfdaddy2ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public narfdaddy2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public narfdaddy2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public narfdaddy2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public narfdaddy2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ListBuilder1> ListBuilder1s
		{
			get
			{
				return this.GetTable<ListBuilder1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="narfdaddy2.ListBuilder1")]
	public partial class ListBuilder1
	{
		
		private int _numRow;
		
		private string _sCat;
		
		private string _sSubcat;
		
		private string _sItem;
		
		private string _sDialog;
		
		public ListBuilder1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numRow", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int numRow
		{
			get
			{
				return this._numRow;
			}
			set
			{
				if ((this._numRow != value))
				{
					this._numRow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sCat", DbType="VarChar(50)")]
		public string sCat
		{
			get
			{
				return this._sCat;
			}
			set
			{
				if ((this._sCat != value))
				{
					this._sCat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSubcat", DbType="VarChar(50)")]
		public string sSubcat
		{
			get
			{
				return this._sSubcat;
			}
			set
			{
				if ((this._sSubcat != value))
				{
					this._sSubcat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sItem", DbType="VarChar(50)")]
		public string sItem
		{
			get
			{
				return this._sItem;
			}
			set
			{
				if ((this._sItem != value))
				{
					this._sItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDialog", DbType="VarChar(MAX)")]
		public string sDialog
		{
			get
			{
				return this._sDialog;
			}
			set
			{
				if ((this._sDialog != value))
				{
					this._sDialog = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
